### ISSUE TITLE
How to generate server_x_test.txt and server_y_test.txt for own dataset?

### ISSUE THREAD

**Issue by RayShing** [xmouyang/ClusterFL#1]
Hello, I am trying to apply ClusterFL to my HAR dataset. I am confused about how to create "server_x_test.txt" and "server_y_test.txt" for the global model. Based on the source code, this data is used for calculating KL distance. However, given that we run the model in the FL setting, should all the data be kept on the client side? How do I generate those data for the server?

**Comment by xmouyang** [comment]
Hi Felix! Sorry for the late reply. The data "server_x_test.txt" is just located on the server to evaluate the clustering relationship of nodes using their model output on the data. In our experiments, we just randomly select a small amount of data samples from each node to make the global data unbiased. Note that we exclude the selected data from the local training and testing set of nodes. We have also tried some synthetic data that is randomly generated (with the same dimension as the real data samples), which is also shown to be able to be effective. You can try both on your data. 

Hope this addresses your problems. Thanks!
